version: '3.8'

services:
  web:
    image: wordpress-ecs_web:fba5753
    build:
      context: ./nginx
    depends_on:
      - app
    ports:
      - "8080:80"
    volumes:
      - ./wordpress:/var/www/html

  app:
    image: wordpress-ecs_app:fba5753
    build:
      context: ./php-fpm
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
      WORDPRESS_DB_CHARSET: utf8mb4
      WORDPRESS_DB_COLLATE: utf8mb4_0900_as_cs
    volumes:
      - ./wordpress:/var/www/html

  db:
    image: mysql:8
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_0900_as_cs
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - ./mysql/conf.d:/etc/mysql/conf.d
      - db:/var/lib/mysql

volumes:
  db:
