---
AWSTemplateFormatVersion: '2010-09-09'
Description: "CloudFront"
Parameters:
  ParentZoneStack:
    Description: 'stack name of parent zone stack based on vpc/zone-*.yaml template.'
    Type: String
  SubDomainNameWithDotOrigin:
    Description: 'Name that is used to create the DNS entry with trailing dot, e.g. ยง{SubDomainNameWithDot}ยง{HostedZoneName}.'
    Type: String
  SubDomainNameWithDot:
    Description: 'Name that is used to create the DNS entry with trailing dot, e.g. ยง{SubDomainNameWithDot}ยง{HostedZoneName}.'
    Type: String
  CustomHeaderName:
    Description: 'The name attached to Header in CloudFront.'
    Type: String
  CustomHeaderValue:
    Description: 'The value attached to Header in CloudFront.'
    Type: AWS::SSM::Parameter::Value<String>
  AcmCertificateARN:
    Description: 'The ACM Certificate ARN for the CloudFront distribution. Must be created in the us-east-1 region!'
    Type: String
Resources:
  CloudFrontDistribution:
    Type: 'AWS::CloudFront::Distribution'
    Properties:
      DistributionConfig:
        Aliases:
          - !Sub
            - '${SubDomainNameWithDot}${HostedZoneName}'
            - SubDomainNameWithDot: !Ref SubDomainNameWithDot
              HostedZoneName: {'Fn::ImportValue': !Sub '${ParentZoneStack}-HostedZoneName'}
        Comment: !Sub
          - '${SubDomainNameWithDot}${HostedZoneName}'
          - SubDomainNameWithDot: !Ref SubDomainNameWithDot
            HostedZoneName: {'Fn::ImportValue': !Sub '${ParentZoneStack}-HostedZoneName'}
        Origins:
          - DomainName: !Sub
              - '${SubDomainNameWithDotOrigin}${HostedZoneName}'
              - SubDomainNameWithDot: !Ref SubDomainNameWithDotOrigin
                HostedZoneName: { 'Fn::ImportValue': !Sub '${ParentZoneStack}-HostedZoneName' }
            Id: 'alb'
            CustomOriginConfig:
              OriginProtocolPolicy: 'https-only'
              OriginReadTimeout: 60
              OriginSSLProtocols:
                - 'TLSv1.2'
            OriginCustomHeaders:
              - HeaderName: !Ref 'CustomHeaderName'
                HeaderValue: !Ref 'CustomHeaderValue'
        CacheBehaviors:
          - PathPattern: wp-content/*
            TargetOriginId: 'alb'
            ViewerProtocolPolicy: 'redirect-to-https'
            AllowedMethods:
              - GET
              - HEAD
            ForwardedValues:
              QueryString: true
              Headers:
                - 'Host'
            DefaultTTL: 604800
            MaxTTL: 604800
            MinTTL: 604800
            Compress: true
          - PathPattern: wp-includes/*
            TargetOriginId: 'alb'
            ViewerProtocolPolicy: 'redirect-to-https'
            AllowedMethods:
              - GET
              - HEAD
            ForwardedValues:
              QueryString: true
              Headers:
                - 'Host'
            DefaultTTL: 604800
            MaxTTL: 604800
            MinTTL: 604800
            Compress: true
          - PathPattern: wp-admin/*
            TargetOriginId: 'alb'
            ViewerProtocolPolicy: 'redirect-to-https'
            AllowedMethods:
              - GET
              - HEAD
              - OPTIONS
              - PUT
              - POST
              - PATCH
              - DELETE
            ForwardedValues:
              Cookies:
                Forward: 'all'
              Headers:
                - 'Authorization'
                - 'CloudFront-Forwarded-Proto'
                - 'Host'
                - 'User-agent'
              QueryString: true
            DefaultTTL: 0
            MaxTTL: 0
            MinTTL: 0
            Compress: true
          - PathPattern: wp-login.php
            TargetOriginId: 'alb'
            ViewerProtocolPolicy: 'redirect-to-https'
            AllowedMethods:
              - GET
              - HEAD
              - OPTIONS
              - PUT
              - POST
              - PATCH
              - DELETE
            ForwardedValues:
              Cookies:
                Forward: 'all'
              Headers:
                - 'Authorization'
                - 'CloudFront-Forwarded-Proto'
                - 'Host'
              QueryString: true
            DefaultTTL: 0
            MaxTTL: 0
            MinTTL: 0
            Compress: true
        DefaultCacheBehavior:
          TargetOriginId: 'alb'
          ViewerProtocolPolicy: 'redirect-to-https'
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
            - PUT
            - POST
            - PATCH
            - DELETE
          ForwardedValues:
            Cookies:
              Forward: 'whitelist'
              WhitelistedNames:
                - 'wordpress_*'
                - 'wp-settings-*'
            Headers:
              - 'Authorization'
              - 'CloudFront-Forwarded-Proto'
              - 'Host'
            QueryString: true
          DefaultTTL: 86400
          MaxTTL: 86400
          MinTTL: 0
          Compress: true
        Enabled: true
        HttpVersion: http2
        IPV6Enabled: false
        PriceClass: 'PriceClass_All'
        ViewerCertificate:
          AcmCertificateArn: !Ref AcmCertificateARN
          SslSupportMethod: 'sni-only'
          MinimumProtocolVersion: TLSv1.2_2021
  Route53RecordSet:
    Type: 'AWS::Route53::RecordSet'
    Properties:
      AliasTarget:
        HostedZoneId: Z2FDTNDATAQYW2 # Magic CloudFront number
        DNSName: !GetAtt 'CloudFrontDistribution.DomainName'
      HostedZoneId: { 'Fn::ImportValue': !Sub '${ParentZoneStack}-HostedZoneId' }
      Name: !Sub
        - '${SubDomainNameWithDot}${HostedZoneName}'
        - SubDomainNameWithDot: !Ref SubDomainNameWithDot
          HostedZoneName: { 'Fn::ImportValue': !Sub '${ParentZoneStack}-HostedZoneName' }
      Type: A
Outputs:
  TemplateVersion:
    Description: 'template version.'
    Value: '12.12.0'
  StackName:
    Description: 'Stack name.'
    Value: !Sub '${AWS::StackName}'
